Feat/author
RedTypes/react-project-kitchen-frontend pull request #107
Opened 2022-05-10 11:59 UTC by grecha1337

2022-05-10 12:10 UTC, grecha1337 reviewed
1 Написал виджет - автор
2 добавил text18Sans ,text16Sans text12Sans 
3 добавил border-style: solid; для BasicAvatar  иначе не отображается бордер
4 кажется колор не везде нужен в иконках
5 в тегах поменял типизацию, ругался линтер

2022-05-10 23:57 UTC, kspshnik requested changes
Вообще круто :)
Основные моменты - это обязательность пропса color в TIconProps - надо для SVG цвет задать _явно_, сам он не возьмёт, вроде, и замена иконки для тэга.
Остальное всё из категории "можно лучше" :)

2022-05-10 23:57 UTC, kspshnik commented on src/widgets/tag.tsx
> -      #{tag} { active? <DeleteIcon color="blue" onClick={(e) => inactiveTag(e)} /> : null }
Блин. Я забыл эту иконку - крестик (DeleteIcon это корзинка)
Уже добавил  <CrossIcon>.

2022-05-10 23:57 UTC, kspshnik commented on src/widgets/tag.tsx
> +      {active && <DeleteIcon color='blue' onClick={(e) => inactiveTag(e)} />}
Мне кажется в этом месте анонимная обёртка не нужна, можно просто передать `onClick={inactiveTag}`.

2022-05-10 23:57 UTC, kspshnik commented on src/widgets/tag.tsx
> -      #{tag} { active? <DeleteIcon color="blue" onClick={(e) => inactiveTag(e)} /> : null }
Мне кажется в этом месте анонимная обёртка не нужна, можно просто передать `onClick={inactiveTag}`.

2022-05-11 18:31 UTC, grecha1337 commented on src/types/styles.types.ts
>  export type TAvatarIconProps = {
ок

2022-05-11 18:32 UTC, grecha1337 commented on src/types/styles.types.ts
> +  color?: string;
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/ui-lib/icons.tsx
> +    stroke: ${({ color }) => color || 'none'};
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/ui-lib/icons.tsx
> +    stroke: ${({ color }) => color || 'none'};
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/ui-lib/icons.tsx
> +    stroke: ${({ color }) => color || 'none'};
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/ui-lib/icons.tsx
> +    stroke: ${({ color }) => color || 'none'};
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/ui-lib/icons.tsx
> +    stroke: ${({ color }) => color || 'none'};
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/ui-lib/icons.tsx
> +    stroke: ${({ color }) => color || 'none'};
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/ui-lib/icons.tsx
> +    stroke: ${({ color }) => color || 'none'};
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/ui-lib/icons.tsx
> +    stroke: ${({ color }) => color || 'none'};
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/ui-lib/icons.tsx
> +    stroke: ${({ color }) => color || 'none'};
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/ui-lib/icons.tsx
> +    stroke: ${({ color }) => color || 'none'};
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/widgets/author/index.tsx
> +const AuthorContainer = styled.div`
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/widgets/author/index.tsx
> +const CrateDate = styled.p`
fixed

2022-05-11 18:32 UTC, grecha1337 commented on src/widgets/likes.tsx
> +  handleClick: (e: React.MouseEvent<SVGSVGElement>) => void,
fixed

2022-05-11 18:34 UTC, grecha1337 commented on src/widgets/likes.tsx
>    return (
Компонент с лайками делал Илья, давай я передам ему инфу, он пофиксит, а то мой(Автор) компонент нужен Гоши, стопит его

2022-05-11 18:35 UTC, grecha1337 commented on src/widgets/likes.tsx
>    return (
Я просто решил еслинт пофиксить)

2022-05-11 18:35 UTC, grecha1337 commented on src/widgets/tag.tsx
> +  handleClick: (e: React.MouseEvent<HTMLButtonElement>, tag: string) => void,
ну тут два параметра, так не получится

2022-05-11 18:35 UTC, grecha1337 commented on src/widgets/tag.tsx
> +  inactiveTag: (e: React.MouseEvent<SVGSVGElement>) => void,
fixed

2022-05-11 18:35 UTC, grecha1337 commented on src/widgets/tag.tsx
>    active: boolean,
fixed

2022-05-11 18:35 UTC, grecha1337 commented on src/widgets/tag.tsx
> +      {active && <DeleteIcon color='blue' onClick={(e) => inactiveTag(e)} />}
fixed

2022-05-11 18:35 UTC, grecha1337 commented on src/widgets/tag.tsx
> -      #{tag} { active? <DeleteIcon color="blue" onClick={(e) => inactiveTag(e)} /> : null }
fixed

2022-05-11 20:10 UTC, grecha1337 commented on src/widgets/tag.tsx
> -      #{tag} { active? <DeleteIcon color="blue" onClick={(e) => inactiveTag(e)} /> : null }
fixed

2022-05-11 20:12 UTC, kspshnik commented on src/widgets/likes.tsx
>    return (
ОК, это надо с Ильёй

2022-05-11 20:13 UTC, kspshnik approved these changes

2022-05-11 21:10 UTC, merged