Feat/author like
RedTypes/react-project-kitchen-frontend pull request #108
Opened 2022-05-10 17:45 UTC by grecha1337

2022-05-11 20:11 UTC, kspshnik requested changes
В основном - дублирование комментариев и замечаний из PR#107

2022-05-11 20:11 UTC, kspshnik commented on src/widgets/author-with-like/index.tsx
> +const AuthorWithLike: FC<TAuthorWithLike> = ({
Может быть, назвать типа HeaderPlate или AuthorPlate?

2022-05-11 20:11 UTC, kspshnik commented on src/widgets/author/index.tsx
> +      <CrateDate>
Очепяток?

2022-05-12 17:57 UTC, closed without merging

2022-05-12 17:57 UTC, grecha1337 commented
реализовано в рамках https://github.com/RedTypes/react-project-kitchen-frontend/pull/119